name: Run the script

on:
  workflow_dispatch:
  schedule:
      - cron: '15 22 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install python-dotenv
    - name: run the script
      run: |
        python ./stock_notifier.py
      env:
        KEY_APLHAVANTAGE: ${{ secrets.KEY_APLHAVANTAGE }}
        NOTIFICATION_MAILBOX: ${{ secrets.NOTIFICATION_MAILBOX }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        PERSONAL_MAILBOX: ${{ secrets.PERSONAL_MAILBOX }}